package com.example.socialtrackingapp.model.entities;

public enum Country {
    NONE(""),
    AFGHANISTAN("Afghanistan"),
    AFRICA_DE_SUD("Africa de Sud"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ARABIA_SAUDITĂ("Arabia Saudită"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIA("Belgia"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOSNIA_HERZEGOVINA("Bosnia Herzegovina"),
    BOTSWANA("Botswana"),
    BRAZILIA("Brazilia"),
    BRUNEI("Brunei"),
    BULGARIA("Bulgaria"),
    BURKINA("Burkina"),
    BURUNDI("Burundi"),
    CAMBODGIA("Cambodgia"),
    CAMERUN("Camerun"),
    CANADA("Canada"),
    CAPUL_VERDE("Capul Verde"),
    CHAD("Chad"),
    CHILE("Chile"),
    CHINA("China"),
    COLUMBIA("Columbia"),
    COMOROS("Comoros"),
    CONGO("Congo"),
    COSTA_RICA("Costa Rica"),
    CROAȚIA("Croația"),
    CUBA("Cuba"),
    CIPRU("Cipru"),
    CEHIA("Cehia"),
    DANEMARCA("Danemarca"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    REPUBLICA_DOMINICANĂ("Rebublica Dominicană"),
    TIMORUL_DE_EST("Timorul de Est"),
    ECUADOR("Ecuador"),
    EGIPT("Egipt"),
    EL_SALVADOR("El Salvador"),
    GUINEEA_ECUATORIALĂ("Guineea Ecuatorială"),
    ELVEȚIA("Elveția"),
    EMIRATELE_ARABE_UNITE("Emiratele Arabe Unite"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ETIOPIA("Etiopia"),
    FIJI("Fiji"),
    FILIPINE("Filipine"),
    FINLANDA("Finlanda"),
    FRANȚA("Franța"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GERMANIA("Germania"),
    GHANA("Ghana"),
    GRECIA("Grecia"),
    GRENADA("Grenada"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea-Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HONDURAS("Honduras"),
    UNGARIA("Ungaria"),
    ISLANDA("Islanda"),
    INDIA("India"),
    INDONEZIA("Indonezia"),
    INSULELE_SOLOMON("Insulele Solomon"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    IRLANDA("Irlanda"),
    ISRAEL("Israel"),
    ITALIA("Italia"),
    JAMAICA("Jamaica"),
    JAPONIA("Japonia"),
    IORDANIA("Iordania"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRIBATI("Kiribati"),
    COREEA_DE_NORD("Correa de Nord"),
    COREEA_DE_SUD("Correa de Sud"),
    KOSOVO("Kosovo"),
    KUWAIT("Kuwait"),
    KYRGYZSTAN("Kyrgyzstan"),
    LAOS("Laos"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBIA("Libia"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIA("Lituania"),
    LUXEMBOURG("Luxembourg"),
    MACEDONIA("Macedonia"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVE("Maldive"),
    MALI("Mali"),
    MALTA("Malta"),
    INSULELE_MARSHALL("Insulele Marshall"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MEXIC("Mexic"),
    MICRONESIA("Micronesia"),
    REPUBLICA_MOLDOVA("Republica Moldova"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MUNTENEGRU("Muntenegru"),
    MAREA_BRITANIE("Marea Britanie"),
    MAROC("Maroc"),
    MOZAMBIC("Mozambic"),
    MYANMAR("Myanmar"),
    NAMIBIA("Namibia"),
    NEPAL("Nepal"),
    OLANDA("Olanda"),
    NOUA_ZEELANDĂ("Noua Zeelandă"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORVEGIA("Norvegia"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PAPUA_NOUA_GUINEEA("Papua Noua Guineea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    POLONIA("Polonia"),
    PORTUGALIA("Portugalia"),
    QATAR("Qatar"),
    ROMÂNIA("România"),
    RUSIA("Rusia"),
    RWANDA("Rwanda"),
    ST_KITTS_AND_NEVIS("St. Kitts and Nevis"),
    ST_LUCIA("St. Lucia"),
    SAMOA("Samoa"),
    SAN_MARINO("San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPORE("Singapore"),
    SIRIA("Siria"),
    SLOVACIA("Slovacia"),
    SLOVENIA("Slovenia"),
    SOMALIA("Somalia"),
    SPANIA("Spania"),
    SRI_LANKA("Sri Lanka"),
    SUA("SUA"),
    SUDAN("Sudan"),
    SUEDIA("Suedia"),
    SURINAM("Surinam"),
    SWAZILAND("Swaziland"),
    TAIWAN("Taiwan"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA("Tanzania"),
    THAILANDA("Thailanda"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURCIA("Turcia"),
    TURKMENISTAN("Turkmenistan"),
    UGANDA("Uganda"),
    UCRAINA("Ucraina"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistan"),
    VATICAN("Vatican"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    YEMEN("Yemen"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe");

    private final String countryAsString;

    Country( String countryAsString ) {
        this.countryAsString = countryAsString;
    }

    public static Country convertStringToCountry( String countryAsString ) {
        for(Country country : Country.values()) {
            if(country.countryAsString.equals(countryAsString)) {
                return country;
            }
        }
        return null;
    }

    @Override
    public String toString() {
        return countryAsString;
    }
}
